### ISSUE TITLE
Search improvements for partial matches of title and description

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/image-service#101]
flagged by @javier-molina during CAB testing 

>Text search:
> 
> None of the searches below result in a hit for https://images-dev.ala.org.au/image/8606f0ef-> bc5f-4dec-87a6-b676abf5c2e3 (Title: "Ahother Lizard"). Yes there is a typo in the title.
> 
> https://images-dev.ala.org.au/?q=Ahother+Lizard
https://images-dev.ala.org.au/?q=Ahother
https://images-dev.ala.org.au/?q=Lizard
> 
> A search for "Adam" that is the creator and Rights holder has a hit
> https://images-dev.ala.org.au/?q=Adam

**Comment by djtfmartin** [comment]
These changes are deployed to images-dev.

**Comment by nickdos** [comment]
QA: I couldn't test the specific search query as the record in question is no longer in the test version. I was able to search for "Another" in prod and the record that matched had the term in the `description` field. Close enough.
