### ISSUE TITLE
Implement object storage for images

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/image-service#111]
Allow the image file storage to utilise object storage systems such as Amazon S3 or OpenStack Swift (as used by NeCTAR).

Related to AtlasOfLivingAustralia/data-management#478

**Comment by sbearcsiro** [comment]
Code reviews:
Image Utils: https://upsource.ala.org.au/image-utils/review/IU-CR-1
https://upsource.ala.org.au/image-service/review/IS-CR-2
https://upsource.ala.org.au/image-service/review/IS-CR-3

**Comment by sbearcsiro** [comment]
Load testing results as discussed in code review: https://images-dev.ala.org.au/~bea18c/

**Comment by javier-molina** [comment]
This has been sitting for almost a year now but Dave confirms this changes from Simon have already been reviewed.
