### ISSUE TITLE
Orphaned images from removed data resources

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/image-service#117]
At images.ala.org.au some of the data resources are data_resource_uids only, indicating a data resource that no longer exists in the collectory. These data resources were removed as they were created in error and had no occurrence records associated with them.

dr_uid | count | prev_dr_name | prev_dr_src
-- | -- | -- | --
dr10141 | 15 | Narrandera Landcare Koala Monitoring | atlasoflivingaustralia
dr10232 | 113 | Wildlife Discovery on your Landcare site using infrared wildlife cameras | atlasoflivingaustralia
dr10531 | 209 | Magical Land of Oz | atlasoflivingaustralia
dr10909 | 3 | Mount Evelyn Fauna and Flora | atlasoflivingaustralia
dr11173 | 1 | Inner West Microbat Monitors | atlasoflivingaustralia
dr11662 | 1 | Tom's Test Project | atlasoflivingaustralia
dr11832 | 10 | I Saw That | atlasoflivingaustralia
dr11935 | 178 | B4C Road Kill Map | atlasoflivingaustralia
dr12464 | 38 | Upper Beaconsfield Wildlife Trauma Reduction | atlasoflivingaustralia
dr13169 | 2 | Cane Toad Challenge (Trial of app for suitability) | atlasoflivingaustralia
dr13424 | 20 | Using Seagrass to monitor the health of marine ecosystems | atlasoflivingaustralia
dr14091 | 1 | Trialling solitary native bee homes | atlasoflivingaustralia
dr14317 | 2 | Wildlife Watch NSC | atlasoflivingaustralia
dr14328 | 1 | Byrrill Creek Golden Vale Biodiversity Project | atlasoflivingaustralia
dr2825 | 49 | Sea Search | atlasoflivingaustralia
dr3371 | 3 | Lifesearch | atlasoflivingaustralia
dr3377 | 1 | North East Dung Beetle Project | atlasoflivingaustralia
dr430 | 78006 | Encyclopedia of Life | wilsoncenter
dr4691 | 132 | Community bird monitoring | atlasoflivingaustralia
dr4707 | 2869 | MEGA Murray Darling Microbat Project | atlasoflivingaustralia
dr4992 | 2 | Northern Territory WildWatch | atlasoflivingaustralia
dr5692 | 12 | Caring for Waterhole Creek | atlasoflivingaustralia
dr7483 | 14 | Environmental assets at risk from bushfire | atlasoflivingaustralia
dr8408 | 7 | Wyangan Creek Wildlife Watch | atlasoflivingaustralia
dr8623 | 9 | Yalgorup Bioblitz 2018 | atlasoflivingaustralia
dr8856 | 287 | Koala Mapping Mackay & Whitsundays Areas | atlasoflivingaustralia
dr8925 | 1 | DoE Test | atlasoflivingaustralia
dr8937 | 1 | Test | atlasoflivingaustralia
dr9035 | 7 | Upside-down Jellyfish in Lake Macquarie | atlasoflivingaustralia
dr9129 | 115 | Bulimba Creek Catchment Nest Box Monitoring project | atlasoflivingaustralia
dr9329 | 15 | Ngururrpa Rangers - Tracks | atlasoflivingaustralia
dr9696 | 142 | Burnside Urban Foresters | atlasoflivingaustralia

**Comment by djtfmartin** [comment]
As we discussed, we can use soft deletes for the images by running:

```
update image set date_deleted=now() where data_resource_uid='dr430';
```

The images can then be purged at a later date using the admin console -> Tools -> 'Purge deleted images' which should remove the images from the database and filesystem.

**Comment by djtfmartin** [comment]
I've done this now for the listed resources, and rebuilt the image index. This issue can be closed.

**Comment by peggynewman** [comment]
Thanks @djtfmartin
