### ISSUE TITLE
Migrate production images from block storage to S3

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/image-service#119]
Migrate all existing images stored in production image service to S3.

**Activities (TBC)**
Define strategy (spin of new VM to run migration job, parallelise, ionice)
Run actual migration
New release (CAB checks)

**Questions**
- How long the migration will take to complete?
- How do we make sure service is not impacted?
- Do we need to remove duplicate and orphan images first?

**Background**
For the past months/years the strategy to manage storage for images has been to expand the filesystem, while we have not reached a hard limit  yet the task requires manual intervention.

In addition cost of storage on S3 is 20% the cost of block storage which make it more appealing.

**Comment by ansell** [comment]
The main issue for object storage is at #111

**Comment by javier-molina** [comment]
Thanks @ansell for pointing that out.

After discussing this in the infrastructure upgrade planning meeting, we came to the conclusion that these two are still separate activities. #111 deals with image-service ability to support other storage back ends, that is the code implementation; while the main goal of this one is to perform the actual migration of existing images in production.
