### ISSUE TITLE
Batch upload was unsuccessful with error "Problem reading files: Unrecognized codec: snappy"

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/image-service#170]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/72474143/194447559-72a0f300-67f5-4d6d-b27e-89c444118ecb.png">

**Comment by cha801p** [comment]
Tested the fix, works fine.

**Comment by yasima-csiro** [comment]
Functional Test results - https://csiroau.sharepoint.com/:x:/r/sites/AtlasofLivingAustralia/Shared%20Documents/Cloud%20Uplift/APIGateway+Cognito/Testing/Image%20service/OIDC%20Intregration%20Test%20-%20Images%20service%20-%20round%203.xlsx?d=w4b73feb07ee64afea1f8ac6004d40113&csf=1&web=1&e=pn3BZi
