### ISSUE TITLE
BIE specimens image load issue

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/image-service#172]
Raised by @timhicks-ala. 

A user's identified a number of species where the specimen photos do not load when clicked, from the BIE gallery or from individual records' pages:
Corymbia novoguinensis https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2908695#gallery
Corymbia latifolia https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2893193#gallery
Balaustion pulcherrimum https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2911816#gallery
Hibbertia ericifolia https://bie.ala.org.au/species/https://id.biodiversity.org.au/taxon/apni/51305464#gallery
Podolepis microcephala https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2904854#gallery
All the cit sci photos seem to load, so it's just an issue with the specimen photos.

**Comment by yasima-csiro** [comment]
Initiated tile re-generation job for all the errored images.

**Comment by yasima-csiro** [comment]
Will initiate the re-generate the tiles job for an image as users complain for now until Simon is back.
