### ISSUE TITLE
Images-test page is returning an error

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/image-service#185]
The following page is returning "An error has occurred" 
https://images-test.ala.org.au/admin/reindexImages

![Image](https://github.com/AtlasOfLivingAustralia/image-service/assets/90439797/16832b68-7878-46a1-bbdc-2841dfd812ca)

- raised by @rosemaryjoconnor

**Comment by sbearcsiro** [comment]
Fixed in [fba6092](https://github.com/AtlasOfLivingAustralia/image-service/pull/180/commits/fba60921bba1eb63cbde8bb5c18d4d24798d1f0b)
