### ISSUE TITLE
Specifying image-service urls in some of the recognised formats processed wrong

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/image-service#187]
According to this issue AtlasOfLivingAustralia/data-management#957 some of the formats specified in this test doesn't work:
https://github.com/AtlasOfLivingAustralia/image-service/blob/a0638b6ae5567595e572c16d637ee90ae7360bc8/src/test/groovy/au/org/ala/images/ImageServiceSpec.groovy#L67

**Comment by sbearcsiro** [comment]
@sadeghim this was caused by some missing configuration in the images-test environment.  This has been rectified in test and should work fine in production.
