### ISSUE TITLE
Updating metadata fields

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/image-service#21]
When I re-ingest a dwca with multimedia extension, It doesn't update the metadata information on the images.

What's the work around this issue?

**Comment by djtfmartin** [comment]
I thought we had fixed this in the biocache. Which specific fields arent updating ?

**Comment by sadeghim** [comment]
In the csv file, license and rightsHolder were swapped. 
Then I re-swapped them and loaded , processed but it didn't update. 
Here are the records: http://biocache.ala.org.au/occurrences/search?q=collection_uid:co65#tab_recordImages

**Comment by djtfmartin** [comment]
Im probably missing something, but this looks ok to me:

http://images.ala.org.au/image/details?imageId=d422020f-a775-4380-af72-9d3998309b0f

https://photos-2.dropbox.com/t/2/AAB7H9d8CGs8ZfuGljMbK7GkbdPaqD7vsjsDUoZjFhjtWQ/12/1952993/png/32x32/1/_/1/2/Screenshot%202016-01-12%2015.03.26.png/EMXbxwEYqvO8PSAHKAc/wQBL7LWIpgZQgMvPb766IvMnqwcx6Qt8fqEDgw_2TUU?size=1280x960&size_mode=3

**Comment by djtfmartin** [comment]
closing. please reopen if there is still an issue/
