### ISSUE TITLE
It is not possible to update metadata with empty value

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/image-service#28]
I am are planning to store user's rating of images as user metadata. It will use two metadata named like and dislike. Each metadata will have a list of user ids.
In scenario where a user first liked an image and then subsequently update the image with a  disliked, the logic breaks as dislike and like metadata will have the user's id. The is because the code does not permit empty values to be updated for a metadata. Permitting empty value will solved this issue.

https://github.com/AtlasOfLivingAustralia/data-management/issues/219

**Comment by pwscsiro** [comment]
https://upsource.ala.org.au/image-service/review/IS-CR-1
