### ISSUE TITLE
webservice image upload: support setting `Image` attributes

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/image-service#3]
When remotely uploading images via `http://images.ala.org.au/ws/uploadImage`, top-level metadata (attributes of the Image class), as opposed to the Image.metaData (arbitrary data). 

In particular there are two fields for `Image` that should be set:
* copyright
* attribution

if those fields are present in the `params.metadata` POSTed data. 

Currently these values are going through to the "System" metadata but do not appear on the output of http://images.ala.org.au/ws/getImageInfo/{imageId} (unless the param `includeMetadata=true` is added.

**Comment by djtfmartin** [comment]
I think we should be sticking with dublin core. So probably the following:
 * license
 * rightsHolder
 * accessRights 

as opposed to copyright ( = license) and attribution ( = rightsHolder)

cc @M-Nicholls @charvolant

**Comment by nickdos** [comment]
Also need to support the "photographer" field... which might be attribution?

**Comment by M-Nicholls** [comment]
the term in the DwC extension is "creator" but we currently use photographer.  it can be different to the attribution though - that's determined by the person that owns the rights.

**Comment by djtfmartin** [comment]
This is done on the master. Just need to deploy to production

**Comment by djtfmartin** [comment]
This is all done now.
