### ISSUE TITLE
Faster image loading API

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/image-service#31]
I see in the biocache-store logs that loading an image whether or not image already exists (which is usually the case) is fairly slow.
One solution that I guess we can have is to create an API that accepts multiple image and return a response showing that which images are already stored in the media store.

This way can reduce the round trip time for calling the individual image loading API for the whole batch.

**Comment by djtfmartin** [comment]
I tracked down the slow performance to the storage of EXIF infromation in the postgres DB (basically an insert per metadata item). Metadata storage is now done as an asynchronous background task (along with thumbnailing, tiling).
