### ISSUE TITLE
Bulk metadata update

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/image-service#33]
Need to be able to run batch updates to image metadata particularly licenses:

e.g. set license for all or a subset of images from a data resource 
- the set default image license in the collectory seems to be over riding the information provided in a Darwin Core archive and it doesn't have an option to set the default back to empty.

Specific example is dr660 (ANFC images) - I'm trying to update the licensing for a subset of the images to "All rights reserved" but the images still have CC-BY_NC on them, see dr660 metadata for file and current settings.

**Comment by djtfmartin** [comment]
Theres a mechanism in place already to retrieve resource level metadata from the collectory and display on image pages. See "Image metadata" section of data resource pages.
