### ISSUE TITLE
Access to admin without ALA-CAS

### ISSUE THREAD

**Issue by JeGoi** [AtlasOfLivingAustralia/image-service#36]
How is it possible to have access to admin of images module without the ALA-CAS?

**Comment by andrevtg** [comment]
This works for pretty much all ALA modules so far:

security.cas.bypass=true

You *DO NOT* disable CAS, instead you turn on bypassing. Login (and/or self-registering) works on Australian CAS and any authenticated user is also an Admin. It is great for testing, not so great for production though.

**Comment by djtfmartin** [comment]
Closing this as @andrevtg answers the question.
