### ISSUE TITLE
Thumbnail for a non-image should show a generic or relevant static icon rather than 404

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/image-service#40]
In the case of non-images being stored in images, the proxyImageThumbnail service currently returns HTTP 404 instead of a replacement generic or static icon:

```
https://images.ala.org.au/image/proxyImageThumbnail?imageId=c14c7ecb-849e-491c-82c3-8b6424b25b0f
```

It would improve browsing using biocache-hub if there was a valid image returned for thumbnail calls for sounds and other media types we are storing in the images service.

**Comment by djtfmartin** [comment]
this is done in grails3 version so i've closed the issue for now (we've no . plans to fix on grails2)

See
https://images-beta.ala.org.au/?fq=recognisedLicence:ALL-RIGHTS-RESERVED

**Comment by ansell** [comment]
Sorry, just assigned you to this and the other completed issues so the project board shows who the issues were done by. Not expecting this on ala-sutcliffe
