### ISSUE TITLE
Prevent duplicate pictures

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/image-service#45]
Comes from Freshdesk ticket https://support.ehelp.edu.au/a/tickets/27235
> The major issue of course was the insertion of bird data into a spider space.
A third problem I will mention again is the urgent need to eliminate identical pictures. It is extremely frustrating when I have to spend many hours wading through thousands of photos which appear in random order and many of them are identical duplicates and some of them appear up to half a dozen times.

**Comment by djtfmartin** [comment]
this is now prevented in the grails3 branch
