### ISSUE TITLE
Public image URLs return 404 when cookie is present but session has expired

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/image-service#5]
Most of the URLs in this app are under the `authenticateOnlyIfLoggedInFilterPattern` filter. This can result in some users seeing missing image icons in apps that show images out of the image-service. 

I am able to replicate this issue in the biocache-hubs by doing the following:
- Visit a page with images, e.g.http://biocache.ala.org.au/occurrences/search?q=pink#tab_recordImages
- logout (if logged in)
- login again but DO NOT CLICK the "Remember me" tick box
- Wait 24 hours (for session to expire) but leave page up in browser
- refresh page - image will be missing (see screen shot)

![image](https://cloud.githubusercontent.com/assets/532845/7447520/e41c6aac-f241-11e4-8e13-6a28f5912abc.png)

Suggested fix is to ensure all public URLs are not under CAS at all. Note that URLs under the `authenticateOnlyIfLoggedInFilterPattern` will not be excluded is included in the `uriExclusionFilter` (it only works against the `uriFilterPattern` - this is a bug/feature).

**Comment by djtfmartin** [comment]
This needs to be tackled as part of the API overhaul for the image-service.
We need a new set of REST based webservices.

**Comment by pwscsiro** [comment]
1. Unable to locate how the authenticateOnlyIfLoggedInFilterPattern is set - checked image-service, userdetails, ala-cas, ala-cas-client, ala-auth.  The only settings I have so far come across are in a property file; userdetails-config.properties which contains possible related settings for uriFilterPattern and uriExclusionFilterPattern. 2. Unable to locate where in image-service URLs can be mapped/un-mapped to these CAS patterns.

**Comment by nickdos** [comment]
via config file. My local version has: `authenticateOnlyIfLoggedInFilterPattern=/,/image/.*,/ws/.*,/webService/.*,/search/.*` (but I think this is out of date).

Example image URL: http://images.ala.org.au/image/proxyImageThumbnail?imageId=c846a703-603c-4c3b-b893-fb9526bd7f43

http://images.ala.org.au/image/details?imageId=4e28d948-79db-43bb-b20f-d93824335e03

should be under authenticateOnlyIfLoggedInFilterPattern.

`/image/.*` -> `/image/details` - look for any other pages that might need this under /images.

**Comment by pwscsiro** [comment]
/images/details and /images/view seem to be the only paths under /images that can be reached by a user, the latter has no additional functionality if the user is logged in, the former may, so have made the above change to ala-install/ansible/roles/image-service/templates/config/config.properties i.e.

authenticateOnlyIfLoggedInFilterPattern=/,/image/details,/ws/.*,/webService/.*,/search/.*

(manually checked UrlMappings.groovy and method names in the image controller in Image-Service)

**Comment by nickdos** [comment]
You've removed the `*` bit from `/ws/.,/webService/.` is there a reason for that? 

E.g. was `/ws/.*,/webService/.*` and you have `/ws/.,/webService/.`

**Comment by temi** [comment]
@pwscsiro , the [fix](https://github.com/AtlasOfLivingAustralia/ala-install/commit/c9951779d29f3f3e64d2bf6e1ecd78183633427d) did not work for me. Uploading an image had problems. For some reason, CAS could not identify the request I sent. When i reverted the pattern to "/image/.*", it worked fine.

**Comment by nickdos** [comment]
OK - image upload requires CAS... so we need to add the specific URL pattern to catch uploads - can't leave as `/image/*`... @temi is the image upload via browser or is it a server-server WS call?

**Comment by temi** [comment]
@nickdos , It is via the browser. It is a form submit to "stageImages" action on "image" controller. But it does not pass the annotation based security check.

**Comment by pwscsiro** [comment]
@temi, @nickdos Does that mean all the alasecured methods need to be in authenticatedOnlyIfLoggedin?

**Comment by temi** [comment]
I think it has to be specifically excluded from it. Nick and Mark knows CAS better than me.

**Comment by nickdos** [comment]
My understanding is that anything with the `@AlaSecured` annotation has to be under CAS otherwise there is no way to know if the user has the required ROLE (passed into annotation via `values=[]`). I'd first try adding each URL path with that annotation (in the [ImageController](https://github.com/AtlasOfLivingAustralia/image-service/blob/master/grails-app/controllers/au/org/ala/images/ImageController.groovy)) as separate entries in `uriFilterPattern` - i.e. force it to be logged in and not the less secure `authenticateOnlyIfLoggedInFilterPattern `. This is just a guess so needs testing/validating... Maybe run this past Mark for sanity check?

**Comment by pwscsiro** [comment]
Checked with Mark also. The relationship between the CAS properties and AlaSecured annotation, if I understand correctly, is that CAS is called according to the rules represented in the properties, ALASecured annotation needs the user's Roles and these are only available if CAS has been called.

**Comment by nickdos** [comment]
@sbearcsiro if you're looking at image-service, could you try fixing this one as a priority, please?
