### ISSUE TITLE
Can't select images or create albums

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/image-service#53]
Grails 3 branch.

Current prod version allows the user to select images by clicking the "tick box" next to each image or using the drop-down "cog" icon to either "select all on page" or "select all matching images".  Once one or more images are selected, the text in the "crumb trail portion of the page (right side)" shows:

![image](https://user-images.githubusercontent.com/532845/59651926-0b93bc80-91cf-11e9-80a7-760e8a529c8e.png)

This functionality appears to be lost in the new version, as neither the "tick boxes" nor the "X selected images" tool (screenshot above) are displayed.

Therefore a user cannot create an album, which is a requirement for exporting images as CSV file.

Fixes:

- [ ] "cog" icon missing on drop-down tool on right side of screen (after doing a search)
- [ ] images from search are missing "tick box"
- [ ] tool to allow an album to be created or to show existing albums is missing, so re-instate

**Comment by djtfmartin** [comment]
Fixed. We've removed the album functionality as it wasnt used and the main reason for using it was to get an export of images.

You can now download image metadata from the search.
