### ISSUE TITLE
uploaded image gets cropped

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/image-service#54]
I tested Biocollect with the new image server and most of the uploads worked as expected. But one image got cropped and a black background was added. The original image used is attached.

[Actual Biocollect record](https://biocollect-test.ala.org.au/sightings/bioActivity/index/97faf08d-fadc-4924-868c-6b5498db3220?returnTo=%2Fsightings%2FbioActivity%2FprojectRecords%2Fb3d8e243-1137-4d26-9e15-c5a6f90815eb) 
[Uploaded image](https://images-dev.ala.org.au/image/6eee3c59-ef18-4680-b182-4c05207210bd)

Attached image -
![Bowie-koala-Australia-Zoo-eye-colour-1000x588](https://user-images.githubusercontent.com/1152259/59651914-fa4ab000-91ce-11e9-84e8-8535533ff4a0.jpg)

**Comment by djtfmartin** [comment]
reproduced locally.
