### ISSUE TITLE
Create album function broken (Grails 3)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/image-service#55]
Grails 3 issue.

https://images-beta.ala.org.au/album/index

- [ ] crumb trail display is not formatted correctly (appears as numbered list, not a crumb trail) and is not integrated into the (new) existing crumb trail (above it).
- [ ] "New album" button not working (see below)
- [ ] "Upload" button redirects to Images home page with alert "Could not find image with id stagedImages!"
- [ ] Confusing link under albums section with text "Desktop version", does nothing when clicked (remove this)?

Click button "New album". 
Expected output: a modal dialog appears: 
![image](https://user-images.githubusercontent.com/532845/59652291-7a254a00-91d0-11e9-8c8e-0c988bfd62eb.png)
Actual output: nothing happens (no error or JS error).

**Comment by djtfmartin** [comment]
Fixed. We've removed the album functionality as it wasnt used and the main reason for using it was to get an export of images.

You can now download image metadata from the search.
