### ISSUE TITLE
Code review required - image-service 1.0.1

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/image-service#61]

**Comment by charvolant** [comment]
Hi Dave,

I've reviewed the changes from 2019-04-29 onwards.

Here are the comments. There are quite a few cases where I don't think that the stylistic differences actually make a difference but I've flagged them anyway.

* AnalyticsServer#76 - Hard link to /data/image-service/config/google-analytics.json no
* ScheuldeMissingImagesBackgroundTask#23 - Needs to create directory if absent
* application.yml#140 - Needs default imageservice.imagestore.inbox (generally needs defaults for things used in config or a graceful failure)
* imageimport.gsp#37 script tag outside body is not rendered
* DarwinCoreField This seems to be a redundant implementation of the GBIF Term vocabularies?
* ImageUtils#76 Pattern could be made static constant
* ImportFieldValueExtractor Is it worth having a separate, reusable regexcache class?
* ImportFileBackgroundTask and friends. I'm a little unclear as to why in some cases the variables are private and some cases they're not
* MapResourceFileGenerator#29 Hard coded service URL(?)
* ResultsPage consider delegation to _pageList, file name and class name don't match
* SearchCriteria/SearchCriteriaDefinition serializable but no serialisation UID
* images.gsp Does <script disposition="head"> work?
* ImageService#25 Transactional is deprecated (appears to be a bad import)
* duplicates.gsp#42, details.gsp#177 remove commented out code (there are other instances, I just haven't found them all)
* areYouSureFragment.gsp, calibrateImageFragment.gsp, ... script outside div. I'm not sure this makes a difference in this case but other fragments have the script enclosed
* tag/index.gsp#10 Still has r:require tags, script is outside body and may not make it through layout

**Comment by djtfmartin** [comment]
these comments have been addressed - thanks @charvolant
