### ISSUE TITLE
Hard coded imageServiceBaseUrl in JS file

### ISSUE THREAD

**Issue by andrevtg** [AtlasOfLivingAustralia/image-service#62]
We found a hard coded URL reference in "plugins/images-client-plugin-0.8/js/ala-image-viewer.js":

```
    var imageServiceBaseUrl = "https://images.ala.org.au";
```

This broke some js interactions in our runtime (can't recall where right now). We are patching this post-install in our setup with `sed`, maybe ansible playbooks should do the same.

**Comment by djtfmartin** [comment]
Hmmm - this should be overriden in the configuration files. There *shouldnt* be a need to use sed.
Im guessing theres a property that hasnt been set in an external configuration file (properties or YAML).

Which version are you using ?

**Comment by andrevtg** [comment]
We saw this behaviour in 0.9 and the code looks the same now on 1.0.1. I am asking my team on how to reproduce the problem

**Comment by djtfmartin** [comment]
@andrevtg Im unable to reproduce these issues so im going to close (tested in multiple environments now). Please reopen if you have any further information. Thanks for opening it.
