### ISSUE TITLE
Images bulk export CSV service contains incorrect URL structures in references field

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/image-service#80]
The bulk export CSV service output contains incorrect URL structures in the references field:

```
$ head -n 2 images-export.csv 
dataResourceUid,occurrenceID,identifier,creator,created,title,format,license,rights,rightsHolder,references,title,description,extension,recognisedLicense,dateDeleted,md5hash,fileSize,width,height,zoomLevels,imageIdentifier,occurrenceID
dr1010,"",https://images.ala.org.au/image/proxyImageThumbnailLarge?imageId=c17dd7e0-e14f-4978-b7ef-5acdce5e63f7,,2012-05-28 09:09:30,,image/jpeg,,,,https://images.ala.org.au/image//image/c17dd7e0-e14f-4978-b7ef-5acdce5e63f7,,,jpg,,,055d85eab895ae868b3d25b2aeb15c82,1025415,2592,1944,5,c17dd7e0-e14f-4978-b7ef-5acdce5e63f7,3580f1df-6c9b-4522-8a70-62f8aaf1b228
```

**Comment by djtfmartin** [comment]
Fixed. Was a problem with the stored procedure.

**Comment by ansell** [comment]
The change to the stored procedure in ala-install around about this date didn't seem to change the code used to generate the references field.

https://github.com/AtlasOfLivingAustralia/ala-install/commit/2b763336c7a4273808f90580cd94d1b08cffdcef#diff-2680528a64d0bac398cd40b841c1a90f

It appears to be fixed, but there there is no commit linked to this.

**Comment by nickdos** [comment]
@djtfmartin can you please respond to @ansell comment above, so we can close this issue?

**Comment by nickdos** [comment]
Bump @djtfmartin .

**Comment by djtfmartin** [comment]
I cant recall, but i have a feeling it was an issue in the inventory, or possibly the generated SQL on production was out of date due to partial runnings of the ansible scripts.
Sorry, I cant be more specific than that.

**Comment by ansell** [comment]
Thanks for clarifying. Just wanted to document a fix if one was known.
