### ISSUE TITLE
Provide a link to the image after a successful single image upload

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/image-service#85]
The current workflow for Single Image Upload ends with a message that the upload was successful, but it is not hyperlinked, so the user needs to manually construct a URL to view the image that was just uploaded. It would be useful if the ID was hyperlinked to the URL to browse the image in the following interface (after a successful upload occurs):

![Screen Shot 2019-09-26 at 12 29 05 pm](https://user-images.githubusercontent.com/82365/65734227-56e63100-e115-11e9-9304-7229b7cf9afc.png)

**Comment by djtfmartin** [comment]
This is done on the develop branch and deployed to images-dev as part of 1.0.11-SNAPSHOT

**Comment by ansell** [comment]
This is working on images-dev for me.
