### ISSUE TITLE
m4a audios from inat are classified as video

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/image-service#87]
like this observation: https://www.inaturalist.org/observations/9888116
https://biocache.ala.org.au/occurrences/6f6ba651-1a83-490e-b9d9-784486342de0
And no media is shown.

**Comment by djtfmartin** [comment]
This will be fixed in version 1.0.10, but will also require some database updates to fix some of the existing images.

**Comment by djtfmartin** [comment]
Example fixed in images-dev

https://images-dev.ala.org.au/image/2bd372cc-f25a-45b8-90b3-9742e159cc7d
