### ISSUE TITLE
Update Licences does not update

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/image-service#93]
Steps to reproduce

1. Navigate to https://images-dev.ala.org.au/admin/dashboard
1. Take note of Licence count and Licence mapping count 
1. Click on Update Licences
On the Update Licences screen
1. Update Licences textbox (add or delete)
1. Update Licence Mapping (add or delete)
1. Click Update

Expected: 
* Dashboard shows new value counts for licences and Licence mapping

Actual 
* Licence count and licence mapping count remain as in step 2.

**Comment by djtfmartin** [comment]
thanks @javier-molina 

Updating licences currently doesn't start a reindex with elastic search. A re-index should reveal a change in the numbers.

Reindexing all the images does take a while for the full set of images (2.6 million) so it is a separate action.

**Comment by djtfmartin** [comment]
Ive added a bit more text to the tools section to try and make this a little more clearer to admin users.

<img width="985" alt="Screen Shot 2019-10-18 at 1 43 16 pm" src="https://user-images.githubusercontent.com/444897/67095199-4291d300-f1ad-11e9-9437-38f75b948cd4.png">

ok to close @javier-molina ?

**Comment by djtfmartin** [comment]
I think this can be closed

**Comment by nickdos** [comment]
QA test passed - saw license count go up by 3 when adding a new mapping. In prod.
