### ISSUE TITLE
Audio files: Play button not showing

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/image-service#94]
* When displaying an audio file it would be great to show the typical triangle play button. At the moment only a dark grey bar is displayed an one intuitively has to click on the lleft of the bar to start playing the audio.

 
![Screen Shot 2019-10-16 at 3 52 55 pm](https://user-images.githubusercontent.com/8326394/66889242-662e0f80-f02d-11e9-9401-2cddc330fadb.png)

* It would be nice if there was a volume control too.

* In addition the audio playback seems to be broken for Safari see below

![Screen Shot 2019-10-16 at 3 53 26 pm](https://user-images.githubusercontent.com/8326394/66889399-f8361800-f02d-11e9-9421-3304fb4c409e.png)

**Comment by djtfmartin** [comment]
This is fixed and deployed on images-dev.

**Comment by djtfmartin** [comment]
Regression - broken on images-dev

**Comment by djtfmartin** [comment]
it is fixed - wrong version was deployed to images-dev.

**Comment by nickdos** [comment]
Play button is showing but there is a bug for the time/time elapsed display ([record](https://images.ala.org.au/image/5137553a-8003-481a-a9eb-942eeda42be0)):

![image](https://user-images.githubusercontent.com/532845/71336619-078c9100-259c-11ea-8192-7c732ad832f3.png)

So I think I'll raise another issue for that.
